Full registration processes. Registration view + form + html page + s…
Fakemrx/DRF-Test-Task pull request #18
Opened 2023-03-14 10:29 UTC by Fakemrx

…uccess page, tests are not done yet. Buyer now attached to user.

2023-03-15 09:19 UTC, Fakemrx commented on buyer/tests/test_buyer_http_methods.py
Check second test, i have problems with it.

2023-03-15 10:02 UTC, xal9wiii4ik commented on buyer/views/registration_view.py
> +        render(response, "register.html", {"form": form, "errors": form.errors})
remove render, we have to use only api

2023-03-15 10:02 UTC, xal9wiii4ik commented on buyer/models.py
> +@receiver(post_save, sender=User)
move to signals.py

2023-03-15 10:02 UTC, xal9wiii4ik commented on buyer/models.py
> +@receiver(post_save, sender=User)
add tests to signals, its will help to us to see where will be error

2023-03-15 11:25 UTC, Fakemrx commented on buyer/models.py
> +@receiver(post_save, sender=User)
Unnecessary anymore, removed signals

2023-03-15 11:25 UTC, Fakemrx commented on buyer/tests/test_buyer_http_methods.py
Solved

2023-03-22 18:01 UTC, xal9wiii4ik commented on buyer/serializers/buyer_serializers.py
> +            User.objects.get(username=value)
Use exist() instead of get+try. Its will be faster

2023-03-22 18:03 UTC, xal9wiii4ik commented on buyer/serializers/buyer_serializers.py
> +            raise serializers.ValidationError("Incorrect full name format.")
Use first/last name and sum up them

2023-03-23 06:46 UTC, Fakemrx commented on buyer/serializers/buyer_serializers.py
> +                "Password must contain at least 1 [A-Z] letter"
It's regular expression's pattern. It's necessary to use "[A-Z]" or "[a-z]" **pattern** to provider correct work of re.search function!

2023-03-23 09:47 UTC, Fakemrx commented on buyer/views/buyer_views.py
> +        return Response(data=request.data, status=status.HTTP_201_CREATED)
@xal9wiii4ik JWT Auth that has token functionality is not done yet.

2023-03-23 13:08 UTC, xal9wiii4ik requested changes

2023-03-23 13:08 UTC, xal9wiii4ik commented on buyer/serializers/buyer_serializers.py
> +                "Password must contain at least 1 [A-Z] letter"
i told you about response message to user. See the lines on which the comments

2023-03-23 13:08 UTC, xal9wiii4ik commented on buyer/views/buyer_views.py
> +        return Response(data=request.data, status=status.HTTP_201_CREATED)
its should be with registration this is mandatory part

2023-03-29 10:53 UTC, xal9wiii4ik commented on buyer/views/buyer_views.py
> +        token = Token.objects.get_or_create(user=user)[0]
we are not soring tokens in db, this is jwt token read more about jwt tokens

2023-04-04 10:01 UTC, xal9wiii4ik approved these changes

2023-04-04 10:11 UTC, merged